#!/bin/bash



if grep -q "DO NOT EDIT THIS FILE" /boot/config.txt; then
    sed -i '/dtparam=i2c_arm=on/d' /boot/firmware/config.txt
    sed -i '/dtparam=i2c_vc=on/d' /boot/firmware/config.txt
    echo "dtparam=i2c_arm=on,i2c_arm_baudrate=400000" >> /boot/firmware/config.txt
    echo "dtparam=i2c_vc=on,i2c_arm_baudrate=400000" >> /boot/firmware/config.txt
    echo "arm_64bit=0" >> /boot/firmware/config.txt
else
    sed -i '/dtparam=i2c_arm=on/d' /boot/config.txt
    sed -i '/dtparam=i2c_vc=on/d' /boot/config.txt
    echo "dtparam=i2c_arm=on,i2c_arm_baudrate=400000" >> /boot/config.txt
    echo "dtparam=i2c_vc=on,i2c_arm_baudrate=400000" >> /boot/config.txt
    echo "arm_64bit=0" >> /boot/config.txt
fi
